# Preliminaries
import os
import sys
import atexit
import source.lib.JMSLab as jms

sys.path.append('config')
sys.dont_write_bytecode = True # Don't write .pyc files

env = Environment(ENV = {'PATH' : os.environ['PATH']},
                  IMPLICIT_COMMAND_DEPENDENCIES = 0,
                  BUILDERS = {'R'         : Builder(action = jms.build_r),
                              'Tablefill' : Builder(action = jms.build_tables),
                              'Stata'     : Builder(action = jms.build_stata),
                              'Matlab'    : Builder(action = jms.build_matlab),
                              'Python'    : Builder(action = jms.build_python),
                              'Lyx'       : Builder(action = jms.build_lyx),
                              'Latex'     : Builder(action = jms.build_latex)})

env.Decider('MD5-timestamp') # Only computes hash if time-stamp changed
Export('env')

jms.start_log('develop', '')

SConscript('source/derived/01_events/SConscript')
SConscript('source/derived/02_macro_political/SConscript')
SConscript('source/derived/03_assets/SConscript')
SConscript('source/derived/04_merging/SConscript')
SConscript('source/analysis/main/tables/SConscript')
SConscript('source/analysis/main/figures/SConscript')
SConscript('source/analysis/appendix/tables/SConscript')
SConscript('source/analysis/appendix/figures/SConscript')
SConscript('source/analysis/numbers/SConscript')
SConscript('source/paper/SConscript')
